#
# This is the GitLab CI configuration file for the mainstream QEMU
# project: https://gitlab.com/qemu-project/qemu/-/pipelines
#
# !!! DO NOT ADD ANY NEW CONFIGURATION TO THIS FILE !!!
#
# Only documentation or comments is accepted.
#
# To use a different set of jobs than the mainstream QEMU project,
# you need to set the location of your custom yml file at "custom CI/CD
# configuration path", on your GitLab CI namespace:
# https://docs.gitlab.com/ee/ci/pipelines/settings.html#custom-cicd-configuration-path
#
# ----------------------------------------------------------------------
#
# QEMU CI jobs are based on templates. Some templates provide
# user-configurable options, modifiable via configuration variables.
#
# See https://qemu-project.gitlab.io/qemu/devel/ci.html#custom-ci-cd-variables
# for more information.
#

include:
  - local: '/.gitlab-ci.d/qemu-project.yml'
default:
    image:
        name: docker-registry.codasip.com/platforms/qemu:0.1.1
        entrypoint: [""]
    interruptible: true
    tags:
        - docker
        - linux
        - nolicense

build_qemu_riscvcheri_64:
    stage: build
    script:
        - scripts/riscv_cheri/build_riscv_cheri riscv64cheri 

build_qemu_riscvcheri_32:
    stage: build
    script:
        - scripts/riscv_cheri/build_riscv_cheri riscv32cheri 

build_qemu_morellocheri:
    stage: build
    script:
        - scripts/riscv_cheri/build_riscv_cheri morello

build_qemu_mipscheri:
    stage: build
    script:
        - scripts/riscv_cheri/build_riscv_cheri mips64cheri128
