#
# This is the GitLab CI configuration file for the mainstream QEMU
# project: https://gitlab.com/qemu-project/qemu/-/pipelines
#
# !!! DO NOT ADD ANY NEW CONFIGURATION TO THIS FILE !!!
#
# Only documentation or comments is accepted.
#
# To use a different set of jobs than the mainstream QEMU project,
# you need to set the location of your custom yml file at "custom CI/CD
# configuration path", on your GitLab CI namespace:
# https://docs.gitlab.com/ee/ci/pipelines/settings.html#custom-cicd-configuration-path
#
# ----------------------------------------------------------------------
#
# QEMU CI jobs are based on templates. Some templates provide
# user-configurable options, modifiable via configuration variables.
#
# See https://qemu-project.gitlab.io/qemu/devel/ci.html#custom-ci-cd-variables
# for more information.
#

include:
  - local: '/.gitlab-ci.d/qemu-project.yml'
variables:
  BUILD_DIR: $CI_PROJECT_DIR/build
  INSTALL_DIR: $CI_PROJECT_DIR/install
  PACKAGE_NAME64: "qemu-system-riscv64cheri"
  PACKAGE_NAME32: "qemu-system-riscv32cheri"
  GIT_FETCH_EXTRA_FLAGS: --quiet --tags
  GIT_DEPTH: 0

stages:
    - build
    - package
    - test

default:
    image:
        name: docker-registry.codasip.com/cheri/qemu:0.1.2
        entrypoint: [""]
    interruptible: true
    tags:
        - docker
        - linux
        - nolicense

build_qemu_riscvcheri_64:
    stage: build
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_PIPELINE_SOURCE == "push"
    script:
        - scripts/riscv_cheri/build_riscv_cheri riscv64cheri 
        - scripts/riscv_cheri/run_tests.sh riscv64cheri
    artifacts:
        when: always
        paths:
        - build_riscv64cheri/riscv64cheri_tests.xml
        - build_riscv64cheri/meson-logs/testlog.junit.xml
        reports:
            junit: 
            - build_riscv64cheri/riscv64cheri_tests.xml
            - build_riscv64cheri/meson-logs/testlog.junit.xml

build_qemu_riscvcheri_32:
    stage: build
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_PIPELINE_SOURCE == "push"
    script:
        - scripts/riscv_cheri/build_riscv_cheri riscv32cheri 
        - scripts/riscv_cheri/run_tests.sh riscv32cheri 
    artifacts:
        when: always
        paths:
        - build_riscv32cheri/riscv32cheri_tests.xml
        - build_riscv32cheri/meson-logs/testlog.junit.xml
        reports:
            junit: 
            - build_riscv32cheri/riscv32cheri_tests.xml
            - build_riscv32cheri/meson-logs/testlog.junit.xml

build_qemu_riscv_64:
    stage: build
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_PIPELINE_SOURCE == "push"
    script:
        - scripts/riscv_cheri/build_riscv_cheri riscv64 
        - scripts/riscv_cheri/run_tests.sh riscv64 
    artifacts:
        when: always
        paths:
        - build_riscv64/riscv64_tests.xml
        - build_riscv64/meson-logs/testlog.junit.xml
        reports:
            junit: 
            - build_riscv64/riscv64_tests.xml
            - build_riscv64/meson-logs/testlog.junit.xml


build_qemu_riscv_32:
    stage: build
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_PIPELINE_SOURCE == "push"
    script:
        - scripts/riscv_cheri/build_riscv_cheri riscv32 
        - scripts/riscv_cheri/run_tests.sh riscv32 
    artifacts:
        when: always
        paths:
        - build_riscv32/riscv32_tests.xml
        - build_riscv32/meson-logs/testlog.junit.xml
        reports:
            junit: 
            - build_riscv32/riscv32_tests.xml
            - build_riscv32/meson-logs/testlog.junit.xml

build_qemu_morellocheri:
    stage: build
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_PIPELINE_SOURCE == "push"
    script:
        - scripts/riscv_cheri/build_riscv_cheri morello
        - scripts/riscv_cheri/run_tests.sh morello
    artifacts:
        when: always
        paths:
        - build_morello/morello_tests.xml
        - build_morello/meson-logs/testlog.junit.xml
        reports:
            junit: 
            - build_morello/morello_tests.xml
            - build_morello/meson-logs/testlog.junit.xml

build_qemu_mipscheri:
    stage: build
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_PIPELINE_SOURCE == "push"
    script:
        - scripts/riscv_cheri/build_riscv_cheri mips64cheri128
        - scripts/riscv_cheri/run_tests.sh mips64cheri128
    artifacts:
        when: always
        paths:
        - build_mips64cheri128/mips64cheri128_tests.xml
        - build_mips64cheri128/meson-logs/testlog.junit.xml
        reports:
            junit: 
            - build_mips64cheri128/mips64cheri128_tests.xml
            - build_mips64cheri128/meson-logs/testlog.junit.xml


nightly_build:
    stage:
        package
    rules:
    - if: $CI_PIPELINE_SOURCE =="schedule"
    script:
        - scripts/riscv_cheri/package $INSTALL_DIR
        - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $INSTALL_DIR/bin/$PACKAGE_NAME32 "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/qemu-cheri/0.0.1/$PACKAGE_NAME32"'
        - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $INSTALL_DIR/bin/$PACKAGE_NAME64 "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/qemu-cheri/0.0.1/$PACKAGE_NAME64"'
        - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $INSTALL_DIR/bin/qemu-img "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/qemu-cheri/0.0.1/qemu-img"'
    artifacts:
        paths:
        - $INSTALL_DIR/bin/$PACKAGE_NAME32
        - $INSTALL_DIR/bin/$PACKAGE_NAME64
        - $INSTALL_DIR/bin/qemu-img
        expire_in: 1 week

tag_build:
    stage:
        package
    rules:
    - if: '$CI_COMMIT_TAG != null'
    script:
        - scripts/riscv_cheri/package $INSTALL_DIR
        - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $INSTALL_DIR/bin/$PACKAGE_NAME32 "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/qemu-cheri/${CI_COMMIT_TAG}/$PACKAGE_NAME32"'
        - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $INSTALL_DIR/bin/$PACKAGE_NAME64 "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/qemu-cheri/${CI_COMMIT_TAG}/$PACKAGE_NAME64"'
        - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $INSTALL_DIR/bin/qemu-img "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/qemu-cheri/${CI_COMMIT_TAG}/qemu-img"'

include:
  - template: Jobs/SAST.gitlab-ci.yml
 
