#
# This is the GitLab CI configuration file for the mainstream QEMU
# project: https://gitlab.com/qemu-project/qemu/-/pipelines
#
# !!! DO NOT ADD ANY NEW CONFIGURATION TO THIS FILE !!!
#
# Only documentation or comments is accepted.
#
# To use a different set of jobs than the mainstream QEMU project,
# you need to set the location of your custom yml file at "custom CI/CD
# configuration path", on your GitLab CI namespace:
# https://docs.gitlab.com/ee/ci/pipelines/settings.html#custom-cicd-configuration-path
#
# ----------------------------------------------------------------------
#
# QEMU CI jobs are based on templates. Some templates provide
# user-configurable options, modifiable via configuration variables.
#
# See https://qemu-project.gitlab.io/qemu/devel/ci.html#custom-ci-cd-variables
# for more information.
#

include:
  - local: '/.gitlab-ci.d/qemu-project.yml'
variables:
  BUILD_DIR: $CI_PROJECT_DIR/build
  INSTALL_DIR: $CI_PROJECT_DIR/install
  PACKAGE_NAME: "qemu_cheri.tar.gz"

stages:
    - build
    - package

default:
    image:
        name: docker-registry.codasip.com/cheri/qemu:0.1.2
        entrypoint: [""]
    interruptible: true
    tags:
        - docker
        - linux
        - nolicense

build_qemu_riscvcheri_64:
    stage: build
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_PIPELINE_SOURCE == "push"
    script:
        - scripts/riscv_cheri/build_riscv_cheri riscv64cheri 

build_qemu_riscvcheri_32:
    stage: build
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_PIPELINE_SOURCE == "push"
    script:
        - scripts/riscv_cheri/build_riscv_cheri riscv32cheri 

build_qemu_riscv_64:
    stage: build
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_PIPELINE_SOURCE == "push"
    script:
        - scripts/riscv_cheri/build_riscv_cheri riscv64 

build_qemu_riscv_32:
    stage: build
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_PIPELINE_SOURCE == "push"
    script:
        - scripts/riscv_cheri/build_riscv_cheri riscv32 

build_qemu_morellocheri:
    stage: build
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_PIPELINE_SOURCE == "push"
    script:
        - scripts/riscv_cheri/build_riscv_cheri morello

build_qemu_mipscheri:
    stage: build
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_PIPELINE_SOURCE == "push"
    script:
        - scripts/riscv_cheri/build_riscv_cheri mips64cheri128

nightly_build:
    stage:
        package
    rules:
    - if: $CI_PIPELINE_SOURCE =="schedule"
    script:
        - scripts/riscv_cheri/package $INSTALL_DIR $CI_PROJECT_DIR/$PACKAGE_NAME
    artifacts:
        paths:
        - $CI_PROJECT_DIR/$PACKAGE_NAME
        expire_in: 1 week

