variables:
  GIT_FETCH_EXTRA_FLAGS: --quiet --tags
  GIT_DEPTH: 0

stages:
    - build
    - test

default:
    image:
        name: docker-registry.codasip.com/cheri/qemu:0.1.2
        entrypoint: [""]
    interruptible: true
    tags:
        - docker
        - linux
        - nolicense

build_all:
    stage: build
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_PIPELINE_SOURCE == "push"
    script:
        - mkdir build
        - cd build
        - cmake -GNinja ..
        - ninja
    artifacts:
        paths:
            - build/simple_test_64
            - build/simple_test_64r
            - build/simple_test_128
            - build/simple_test_128m
            - build/simple_test_128r
            - build/simple_test_256
        expire_in: 8 hours

simple_tests:
    stage: test
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_PIPELINE_SOURCE == "push"
    script:
        - cd build
        - ./simple_test_64
        - ./simple_test_64r
        - ./simple_test_128
        - ./simple_test_128m
        - ./simple_test_128r
        - ./simple_test_256
